### PR TITLE
Use latest configuration on Identity bootup (resolves #414)

### LINKED ISSUE #414: Identity should use last set valid config on bootup
Consolidate the config retrieval for bootup scenario. Currently it is being retrieved twice, once for last set value and once with last set value for current event, which may return different results or block on incorrect configuration.
Ref: IdentityExtension forceSyncIdentifiers, readyForSyncIdentifiers.

### PR DESCRIPTION
**Pull request by kevinlind**
## Description

Currently, Identity uses the first set Configuration shared state when processing the force sync during boot up. This causes issues when the first Configuration is not valid. Instead, the Identity boot sequence should use the last set Configuration shared state when processing the force sync event. This way, if the first set Configuration state is invalid, then the next set Configuration state can be used to initialize the Identity extension.

- Refactor `readyForSyncIdentifiers` to take in a Map of the configuration state instead of getting the configuration state from an Event. In addition, update the `latestValidConfig` if the configuration state contains a `experienceCloud.org` value. This is similar to the iOS Swift implementation.
- Update `forceSyncIdentifiers` to use the refactored `readyForSyncIdentifiers`, ensuring to pass `null` to `getSharedState()` which will retrieve the last set Configuration state.
- Refactor `handleSyncIdentifiers` to remove the configuration parameter. As `latestValidConfig` is updated for each sync call, `handleSyncIdentifiers` just needs to use it for the configuration state. This is similar to the iOS Swift implementation.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java [hunk 1]
```diff
@@ -860,31 +844,22 @@ boolean handleSyncIdentifiers(
...
+            // sanity check, should never get here as latestValidConfig set from
+            // readyForEvent/readyForSyncIdentifiers
+            // can't process this event. return false to break execution loop
+            Log.debug(
+                    IdentityConstants.LOG_TAG,
+                    LOG_SOURCE,
+                    "handleSyncIdentifiers : Unable to process sync identifiers request as the"
+                            + " configuration did not contain a valid Experience Cloud"
+                            + " organization ID. Will attempt to process event when a valid"
+                            + " configuration is received.");
```
Comment (emdobrin) [inline code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java:857]: Here there will be no other attempt for this request, let's adjust the log comment to capture that:
```
"handleSyncIdentifiers: Ignoring the Sync Identifiers call as last valid config is empty."
```

File: code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java [hunk 2]
```diff
@@ -860,31 +844,22 @@ boolean handleSyncIdentifiers(
...
-                        IdentityConstants.LOG_TAG,
-                        LOG_SOURCE,
-                        "handleSyncIdentifiers : Unable to process sync identifiers request as the"
-                                + " configuration did not contain a valid Experience Cloud"
-                                + " organization ID. Will attempt to process event when a valid"
-                                + " configuration is received.");
-                return false;
-            }
+        if (latestValidConfig == null) {
+            // sanity check, should never get here as latestValidConfig set from
```
Comment (emdobrin) [inline code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java:848]: nit: this should not have any impact on the flow, but for consistency with iOS can we do this sanity check first thing in this method?

File: code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java [hunk 3]
```diff
@@ -815,32 +813,18 @@ void handleOptOut(final Map<String, Object> configuration) {
...
-                    IdentityConstants.LOG_TAG,
-                    LOG_SOURCE,
-                    "handleSyncIdentifiers : Ignoring the Sync Identifiers call because the"
-                            + " configuration was null.");
-            return false;
-        }
-
+    boolean handleSyncIdentifiers(final Event event, final boolean forceSync) {
         // do not even extract any data if the config is opt_out.
         if (privacyStatus == MobilePrivacyStatus.OPT_OUT) {
```
Comment (emdobrin) [inline code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java:829]: shouldn't we use latestValidConfig.privacyStatus instead and remove L861->L869?

File: code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java [hunk 4]
```diff
@@ -894,14 +869,14 @@ boolean handleSyncIdentifiers(
         }
 
         // if the marketingCloudServer is null or empty use the default server
-        if (StringUtils.isNullOrEmpty(currentEventValidConfig.marketingCloudServer)) {
-            currentEventValidConfig.marketingCloudServer = IdentityConstants.Defaults.SERVER;
+        if (StringUtils.isNullOrEmpty(latestValidConfig.marketingCloudServer)) {
+            latestValidConfig.marketingCloudServer = IdentityConstants.Defaults.SERVER;
```
Comment (emdobrin) [inline code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java:873]: I find it odd that we update properties of latestValidConfig as part of this method. Instead ConfigurationSharedStateIdentity should take care of replacing null/empty values with the default server

File: code/integration-tests/src/androidTest/java/com/adobe/marketing/mobile/integration/identity/IdentityIntegrationTests.kt [hunk 5]
```diff
@@ -216,6 +216,74 @@ class IdentityIntegrationTests {
...
     }
 
+    @Test(timeout = 5_000)
+    fun testIdentitySendsForceSyncRequestOnLaunchOnValidConfig() {
+        SDKHelper.resetSDK()
+        ServiceProviderModifier.reset()
+
+        overrideNetworkService()
+
+        MobileCore.setApplication(ApplicationProvider.getApplicationContext())
```
Comment (emdobrin) [inline code/integration-tests/src/androidTest/java/com/adobe/marketing/mobile/integration/identity/IdentityIntegrationTests.kt:226]: should we cover these in the setup instead?

File: code/integration-tests/src/androidTest/java/com/adobe/marketing/mobile/integration/identity/IdentityIntegrationTests.kt [hunk 6]
```diff
@@ -216,6 +216,74 @@ class IdentityIntegrationTests {
...
+        MobileCore.setLogLevel(LoggingMode.VERBOSE)
```
Comment (emdobrin) [inline code/integration-tests/src/androidTest/java/com/adobe/marketing/mobile/integration/identity/IdentityIntegrationTests.kt:227]: used for debugging or can it be removed?

File: code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java (hunk 4 above)
Comment (kevinlind) [reply code/identity/src/main/java/com/adobe/marketing/mobile/identity/IdentityExtension.java]: ConfigurationSharedStateIdentity already sets marketingCloudServer to the default if null/empty, so this check is not needed. I went ahead and made this class immutable as it's odd to have a class like this which is mutable.

File: code/integration-tests/src/androidTest/java/com/adobe/marketing/mobile/integration/identity/IdentityIntegrationTests.kt (hunk 5 above)
Comment (kevinlind) [reply code/integration-tests/src/androidTest/java/com/adobe/marketing/mobile/integration/identity/IdentityIntegrationTests.kt]: I refactored this test case. I originally thought I needed to restart the SDK, but I only needed to set the configuration and allow setUp to register the extensions for me.

File: code/identity/src/main/java/com/adobe/marketing/mobile/identity/ConfigurationSharedStateIdentity.java [hunk 7]
```diff
@@ -83,6 +67,33 @@ void getConfigurationProperties(final Map<String, Object> sharedState) {
...
+    @NonNull MobilePrivacyStatus getPrivacyStatus() {
+        return privacyStatus;
+    }
+
+    /**
+     * The Experience Cloud server.
+     *
+     * @return the Experience Cloud server; defaults to {@link Defaults#SERVER}
+     */
+    @NonNull String getMarketingCloudServer() {
```
Comment (emdobrin) [inline code/identity/src/main/java/com/adobe/marketing/mobile/identity/ConfigurationSharedStateIdentity.java:93]: since you did a bunch of changes in this class, can we also rename these methods and properties marketingCloudServer -> experienceCloudServer

File: code/identity/src/main/java/com/adobe/marketing/mobile/identity/ConfigurationSharedStateIdentity.java [hunk 8]
```diff
@@ -27,52 +28,35 @@
...
                         sharedState,
                         IdentityConstants.JSON_EXPERIENCE_CLOUD_SERVER_KEY,
                         Defaults.SERVER);
 
-        if (StringUtils.isNullOrEmpty(this.marketingCloudServer)) {
+        if (StringUtils.isNullOrEmpty(server)) {
             this.marketingCloudServer = Defaults.SERVER;
+        } else {
+            this.marketingCloudServer = server;
         }
```
Comment (emdobrin) [inline code/identity/src/main/java/com/adobe/marketing/mobile/identity/ConfigurationSharedStateIdentity.java:60]: nit: can use one-liner

**Review by yangyansong-adbe — APPROVED** [review]
